[workspace]
members = [
    "collections",
    "concurrency_and_async",
    "crawler",
    "err_handling",
    "functional_features",
    "generic_traits_lifetimes", 
    "io_closure_oop_pattern_unsafe",
    "module_system",
    "ownership",
    "playground",
    "rust_basics",
    "smart_pointer",
    "structured_data",
    "test_in_rust", 
    "vector_search",
]
resolver = "2"
