[package]
name = "structured_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# those two are for displaying enum
#strum = "0.22.0"
#strum_macros = "0.22.0"
